dymensionxyz/roller

- LICENSE
---
For Author:
---
For Reviewer:
---
> chore: added license file

- install.sh
---
For Author:
---
For Reviewer:
---
> feat: Added installation script for mac os

- cmd/config/init/init.go
- install.sh
---
For Author:
---
For Reviewer:
---
> feat: removed prompt from installation script

- cmd/config/init/consts.go
- cmd/config/init/error_handler.go
- cmd/config/init/flags.go
- cmd/config/init/init.go
- cmd/config/init/unique_rollapp_id.go
- go.mod
- go.sum
- test/config/init/init_test.go
---
For Author:
---
For Reviewer:
---
> feat: rollapp id verification

- cmd/config/init/consts.go
- cmd/config/init/flags.go
- cmd/config/init/init.go
- cmd/config/init/keys.go
- cmd/config/init/unique_rollapp_id.go
- cmd/register/register.go
- test/config/init/init_test.go
---
For Author:
---
For Reviewer:
---
> feat: Add ability to switch between different hub environments

- cmd/config/init/DALightClient.go
- cmd/register/register.go
- install.sh
---
For Author:
---
For Reviewer:
---
> feat: Add output formatting for `roller register` command

- cmd/config/init/consts.go
- cmd/config/init/init.go
- cmd/config/init/keys.go
- cmd/register/bash_commands.go
- cmd/register/register.go
- cmd/relayer/start/create_ibc_channel.go
- cmd/relayer/start/get_active_src_channel.go
- cmd/relayer/start/get_dst_connection_id.go
- cmd/relayer/start/start.go
- cmd/root.go
- cmd/sequencer/start/start.go
- cmd/utils/bash_commands.go
- cmd/utils/error_handling.go
- go.sum
- test/config/init/init_test.go
---
For Author:
---
For Reviewer:
---
> feat: Add ability to run the relayer

- cmd/config/init/init.go
- cmd/config/init/keys.go
- cmd/config/init/output.go
- cmd/config/init/rollapp.go
- cmd/consts/consts.go
- cmd/keys/keys.go
- cmd/keys/list/list.go
- cmd/register/bash_commands.go
- cmd/register/register.go
- cmd/root.go
- cmd/sequencer/start/start.go
- cmd/utils/error_handling.go
- cmd/utils/keys.go
- test/config/init/testutils/keys.go
- test/config/init/testutils/rollapp.go
---
For Author:
---
For Reviewer:
---
> feat: Add ability to list roller addresses with `roller keys list` command

- cmd/config/init/consts.go
- cmd/config/init/init.go
- cmd/consts/consts.go
- cmd/register/register.go
- cmd/relayer/start/start.go
- cmd/sequencer/start/start.go
- cmd/utils/balance.go
- cmd/utils/error_handling.go
- cmd/utils/output.go
---
For Author:
---
For Reviewer:
---
> feat: Add Balance Verification for Balance-Required Commands

- cmd/da-light-client/start/start.go
- cmd/utils/network.go
---
For Author:
---
For Reviewer:
---
> feat: Add celestia balance verification

- cmd/config/init/flags.go
- cmd/config/init/genesis.go
- test/config/init/goldens/init_with_flags/rollapp/config/genesis.json
- test/config/init/goldens/init_without_flags/rollapp/config/genesis.json
- test/config/init/testutils/rollapp.go
---
For Author:
---
For Reviewer:
---
> feat: Add automatic rollapp relayer funding in the genesis file

- cmd/relayer/start/start.go
---
For Author:
---
For Reviewer:
---
> chore: remove the `rly start` command

- .gitignore
- Makefile
---
For Author:
---
For Reviewer:
---
> feat: added Makefile with build and install targets

- cmd/relayer/start/create_ibc_channel.go
---
For Author:
---
For Reviewer:
---
> fix: added update clients command after client creation

- cmd/sequencer/start/start.go
New output:
```
💈 The Rollapp sequencer is running on your local machine!
💈 Default endpoints:
💈 EVM RPC: http://0.0.0.0:8545
💈 Node RPC: http://0.0.0.0:26657
💈 Rest API: http://0.0.0.0:1317
💈 Log file path:  /Users/mtsitrin/.roller_local_interactive/rollapp/rollapp.log
💈 To interact with the rollapp through CLI:
/Users/mtsitrin/Applications/dymension/rollapp/build/rollapp_evm --home /Users/mtsitrin/.roller_local_interactive/rollapp keys list --keyring-backend test
```
vs old output:
```
💈 The Rollapp sequencer is running on your local machine!
💈 EVM RPC: http://0.0.0.0:8545
💈 Node RPC: http://0.0.0.0:26657
💈 Rest API: http://0.0.0.0:1317
```
---
For Author:
---
For Reviewer:
---
> feat: roller prints metadata on sequencer run

- .gitignore
- cmd/da-light-client/start/start.go
- cmd/relayer/start/start.go
- cmd/run/run.go
- cmd/run/services_info.go
- cmd/run/services_status.go
- cmd/sequencer/start/start.go
- cmd/utils/log.go
---
For Author:
---
For Reviewer:
---
> feat: Add services log files and ports to roller run output

- .gitignore
- cmd/consts/consts.go
- cmd/run/services_status.go
---
For Author:
---
For Reviewer:
---
> feat: Add Continuous Status Monitoring for DA LC and sequencer

- cmd/run/services_status.go
- cmd/run/ui.go
---
For Author:
---
For Reviewer:
---
> chore: Add rollapp ID and Hub ID info to run output

- cmd/config/init/da_light_client.go
- cmd/consts/consts.go
- cmd/da-light-client/start/start.go
- cmd/utils/balance.go
- cmd/utils/fetch_accounts_data.go
---
For Author:
---
For Reviewer:
---
> feat: replaced celestia default da network of arabica with mocha

- cmd/config/init/rollapp.go
- cmd/register/bash_commands.go
- cmd/utils/keys.go
---
For Author:
---
For Reviewer:
---
> feat: added gentx_seq call on init

- install.sh
---
For Author:
---
For Reviewer:
---
> chore: Add support for multiple environments in the installation script

- cmd/config/init/init.go
- cmd/consts/consts.go
- cmd/register/register.go
- cmd/run/run.go
- cmd/utils/output.go
- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> feat: Add loading spinner with status on roller init, register and run

- cmd/config/init/init.go
- cmd/register/register.go
- cmd/utils/error_handling.go
---
For Author:
---
For Reviewer:
---
> fix: Fixed spinner cursor removal bug

- cmd/register/register.go
---
For Author:
---
For Reviewer:
---
> fix: register show output

- cmd/config/init/init.go
- cmd/consts/consts.go
- cmd/register/register.go
- config/config.go
---
For Author:
---
For Reviewer:
---
> feat: denom accepts 3-6 letters

- cmd/run/run.go
---
For Author:
---
For Reviewer:
---
> chore: Add loading spinner while stopping run services

- cmd/config/init/consts.go
---
For Author:
---
For Reviewer:
---
> fix: updated silknodes domain

- cmd/da-light-client/start/start.go
- cmd/run/run.go
- data_layer/celestia/celestia.go
---
For Author:
---
For Reviewer:
---
> chore: Migrate celestia to use the arabica network

- sequencer/status.go
---
For Author:
---
For Reviewer:
---
> feat: Add rollapp height to run output

- config/chainid.go
- config/config.go
---
For Author:
---
For Reviewer:
---
> fix: using evmos validation for rollappID

- cmd/config/init/interactive.go
- config/chainid.go
---
For Author:
---
For Reviewer:
---
> fix: Verifying unique rollapp ID immediately in interactive flow 

- cmd/run/services_status.go
- cmd/run/ui.go
- cmd/utils/balance.go
---
For Author:
---
For Reviewer:
---
> fix: Display balance on roller run in the bigger token denom

- cmd/config/init/flags.go
- cmd/config/init/interactive.go
---
For Author:
---
For Reviewer:
---
> fix: Make interactive flow exit on interrupt

- data_layer/celestia/celestia.go
- utils/service_manager/service.go
---
For Author:
---
For Reviewer:
---
> fix: Avoid panic on failure to fetch da account data

- install.sh
---
For Author:
---
For Reviewer:
---
> chore: Updated installation script for release

- cmd/utils/balance.go
---
For Author:
---
For Reviewer:
---
> fix: Change DYM decimals to 18 instead of 6

- cmd/config/init/interactive.go
---
For Author:
---
For Reviewer:
---
> chore: change default DA to celestia

- cmd/sequencer/start/start.go
---
For Author:
---
For Reviewer:
---
> chore: Changed sequencer log level to debug

- cmd/config/init/consts.go
- cmd/config/init/init.go
- cmd/config/init/relayer.go
- cmd/sequencer/start/start.go
- config/config.go
---
For Author:
---
For Reviewer:
---
> chore: Updated devnet gas prices to 0.25udym

- cmd/register/bash_commands.go
- cmd/register/register.go
---
For Author:
---
For Reviewer:
---
> fix: pass gas prices on roller register

- cmd/sequencer/start/start.go
---
For Author:
---
For Reviewer:
---
> fix: Enable Remote Connections by Exposing RollApp's JSON RPC Endpoint on 0.0.0.0

- .github/workflows/build.yml
- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> Fix: Build CD flow roller from the release tag

- cmd/root.go
- cmd/services/load/load.go
- cmd/services/services.go
---
For Author:
---
For Reviewer:
---
> feat: Add 'roller services load' command to load the different RollApp services

- cmd/config/init/genesis.go
Closes: #293 & #168
Note: I'm just implement this without writing test cases. If needed, please feel free to implement it by yourself with additional code and close this PR.
```bash
rollapp_evm --home ~/.roller/rollapp start 2>&1 > /dev/null &
rollapp_evm --home ~/.roller/rollapp q bank denom_metadata
```
```yaml
metadatas:
- base: uRAX
denom_units:
- aliases: []
denom: uRAX
exponent: 0
- aliases: []
denom: RAX
exponent: 18
description: Denom metadata for RAX (uRAX)
display: RAX
name: Rax
symbol: RAX
uri: ""
uri_hash: ""
pagination:
next_key: null
total: "1"
```
---
For Author:
---
For Reviewer:
---
> feat: add bank denom metadata to rollapp genesis

- cmd/config/init/rollapp.go
- cmd/sequencer/start/start.go
---
For Author:
---
For Reviewer:
---
> fix: removed json-rpc flag from sequencer start

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> Chore: Update compile_locally script to utilize rollapp-evm repository

- data_layer/celestia/celestia.go
---
For Author:
---
For Reviewer:
---
> chore: changed celestia da config to have gas prices

- cmd/da-light-client/start/start.go
- data_layer/avail/avail.go
- data_layer/celestia/celestia.go
- data_layer/da_layer.go
- data_layer/damock/damock.go
---
For Author:
---
For Reviewer:
---
> chore: Add an optional `metrics-endpoint` flag to set the celestia light client metric endpoint

- cmd/config/init/consts.go
- cmd/config/init/flags.go
- cmd/config/init/interactive.go
- cmd/config/init/keys.go
- cmd/utils/keys.go
- config/config.go
---
For Author:
---
For Reviewer:
---
> feat: added vm type parameter

- cmd/config/init/rollapp.go
- sequencer/metric.go
- sequencer/utils.go
- test/config/init/testutils/keys.go
---
For Author:
---
For Reviewer:
---
> chore: Enable dymint HTTP metric server by default

- cmd/config/init/rollapp.go
---
For Author:
---
For Reviewer:
---
> chore: Change RPC address from localhost to 0.0.0.0

- data_layer/celestia/celestia.go
---
For Author:
---
For Reviewer:
---
> chore: updated da config

- cmd/config/init/flags.go
---
For Author:
---
For Reviewer:
---
> chore: Set default decimals to 6 on non evm rollapps

- cmd/config/init/interactive.go
- config/config.go
---
For Author:
---
For Reviewer:
---
> chore: Validate rollapp id `name_uniqueID-revision` format only when using EVM rollapps

- data_layer/avail/avail.go
---
For Author:
---
For Reviewer:
---
> chore: Update Avail RPC endpoint

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: Upgrade rollapp-evm version

- cmd/config/init/rollapp.go
---
For Author:
---
For Reviewer:
---
> fix: Set rollapp default listen addr to 0.0.0.0:26657

- cmd/keys/export/export.go
- data_layer/avail/avail.go
- data_layer/celestia/celestia.go
- data_layer/da_layer.go
- data_layer/damock/damock.go
---
For Author:
---
For Reviewer:
---
> feat: Avail - Support for Exporting Private Key

- cmd/utils/bash_commands.go
---
For Author:
---
For Reviewer:
---
> fix: relayer won't print errors on the stdout, only in logfile

- cmd/migrate/migrate.go
- cmd/migrate/v_0_1_6.go
- sequencer/config.go
---
For Author:
---
For Reviewer:
---
> chore: Update CORS Configuration to Use '*' as Default

- cmd/relayer/start/start.go
---
For Author:
---
For Reviewer:
---
> chore: Reduce sleep interval between update clients and relay packets

- relayer/create_ibc_channel.go
- relayer/relayer_manager.go
---
For Author:
---
For Reviewer:
---
> Chore: Update Relayer Status to Represent Various Stages of Channel Creation

- cmd/relayer/start/start.go
- relayer/create_ibc_channel.go
- relayer/periodic_commands.go
---
For Author:
---
For Reviewer:
---
> chore: Add `relay-acks` to the relayer periodic commands

- relayer/periodic_commands.go
---
For Author:
---
For Reviewer:
---
> chore: Remove `-l` flag from `rly relay-packets`

- cmd/config/config.go
- cmd/config/set/rollapp_rpc.go
- cmd/config/set/set.go
- cmd/relayer/start/start.go
- cmd/run/run.go
- cmd/run/services_info.go
- cmd/sequencer/start/start.go
- cmd/utils/fetch_accounts_data.go
- go.mod
- go.sum
- relayer/query.go
- sequencer/config.go
- sequencer/query.go
- sequencer/sequencer_manager.go
- sequencer/status.go
---
For Author:
---
For Reviewer:
---
> feat: Add command to modify rollapp rpc port

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: Upgrade relayer and rollapp-evm dependencies

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: Upgrade rollapp-evm

- sequencer/config.go
- test/config/init/goldens/init_with_flags/rollapp/config/app.toml
- test/config/init/goldens/init_without_flags/rollapp/config/app.toml
---
For Author:
---
For Reviewer:
---
> chore: Enable RollApp API unsafe C.O.R.S access by default

- cmd/relayer/channel/show/show.go
- cmd/relayer/start/start.go
- relayer/create_ibc_channel.go
- relayer/relayer_manager.go
change relayer channel show to read status from file
---
For Author:
---
For Reviewer:
---
> fix: removed hard coded override flag

- cmd/run/run.go
---
For Author:
---
For Reviewer:
---
> feat: Add a `no-output` flag to `roller run`

- cmd/keys/list/list.go
---
For Author:
---
For Reviewer:
---
> chore: Add JSON output support to `roller keys list` command

- cmd/config/init/unique_rollapp_id.go
- test/config/init/goldens/init_with_flags/relayer/config/config.yaml
- test/config/init/goldens/init_with_flags/rollapp/config/client.toml
- test/config/init/goldens/init_with_flags/rollapp/config/dymint.toml
- test/config/init/goldens/init_with_flags/rollapp/config/genesis.json
- test/config/init/goldens/init_without_flags/relayer/config/config.yaml
- test/config/init/goldens/init_without_flags/rollapp/config/client.toml
- test/config/init/goldens/init_without_flags/rollapp/config/dymint.toml
- test/config/init/goldens/init_without_flags/rollapp/config/genesis.json
- test/config/init/init_test.go
---
For Author:
---
For Reviewer:
---
> chore: Modify EVM rollapp unique ID validation based on EIP155

- install.sh
… script
---
For Author:
---
For Reviewer:
---
> feat: Enable tag-specific roller installation 

- cmd/relayer/start/start.go
---
For Author:
---
For Reviewer:
---
> chore: updated updateClient cmd to run every hour

- cmd/utils/bash_commands.go
---
For Author:
---
For Reviewer:
---
> chore: Print function call error if any in the relayer crons

- cmd/config/init/consts.go
- cmd/config/init/flags.go
- cmd/config/init/interactive.go
---
For Author:
---
For Reviewer:
---
> chore: Added froopyland as an option to the network list

- cmd/sequencer/sequencer.go
- cmd/sequencer/status/status.go
- test/config/init/init_test.go
---
For Author:
---
For Reviewer:
---
> feat: Add a sequencer status command

- sequencer/config.go
SHOULD BE MERGED AFTER https://github.com/dymensionxyz/dymint/pull/452
---
For Author:
---
For Reviewer:
---
> chore: increased default empty block timeout to 1 hour

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: updated rollapp-evm in the script to v0.1.0-rc5

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> fix: update compile_locally rollapp-evm ver

- cmd/migrate/migrate.go
- cmd/migrate/v0_1_11.go
- cmd/migrate/v0_1_9.go
---
For Author:
---
For Reviewer:
---
> chore: Add migrate to 0.1.9 to update empty max block time

- cmd/migrate/migrate.go
- cmd/migrate/v_0_1_12.go
- data_layer/celestia/celestia.go
---
For Author:
---
For Reviewer:
---
> chore: Change celestia gas prices to 1

- sequencer/status.go
---
For Author:
---
For Reviewer:
---
> chore: Display "Unhealthy" rather than "Stopped, restarting" when the sequencer is unhealthy

- .github/workflows/e2e.yml
- scripts/ibc_relay_tester.sh
---
For Author:
---
For Reviewer:
---
> chore: Add an end to end test workflow

- cmd/config/init/flags.go
- cmd/config/init/interactive.go
- config/config.go
- data_layer/da_layer.go
- data_layer/damock/damock.go
---
For Author:
---
For Reviewer:
---
> chore: Allow mock da on a non-local hub

- cmd/run/services_info.go
- cmd/sequencer/start/start.go
- sequencer/config.go
- sequencer/sequencer_manager.go
---
For Author:
---
For Reviewer:
---
> fix: Read output ports from config files

- sequencer/config.go
---
For Author:
---
For Reviewer:
---
> fix: dymint expect mock in config instead of local

- cmd/migrate/v0_1_11.go
- sequencer/config.go
---
For Author:
---
For Reviewer:
---
> fix: changed default empty blocks to 90s

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: upgrade rollapp evm version

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: updated relayer version

- cmd/config/export/export.go
- cmd/config/export/types.go
---
For Author:
---
For Reviewer:
---
> chore: Update `roller config export` structure

- cmd/config/init/init.go
- cmd/config/init/relayer.go
- cmd/migrate/migrate.go
- cmd/migrate/v_0_1_13.go
- cmd/utils/bash_commands.go
- relayer/config.go
---
For Author:
---
For Reviewer:
---
> fix: Add a migration to update the relayer path

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: updated evm to v0.1.8 and relayer to v0.1.3

- README.md
---
For Author:
---
For Reviewer:
---
> docs: Add a local development section to the readme

- cmd/migrate/v_0_1_13.go
- sequencer/config.go
---
For Author:
---
For Reviewer:
---
> chore: update blocktime to 3600s

- cmd/config/set/rollapp_rpc.go
- cmd/migrate/migrate.go
- cmd/migrate/v_0_1_13.go
- cmd/migrate/v_0_1_4.go
- cmd/migrate/v_0_1_5.go
- cmd/migrate/v_0_1_6.go
- relayer/config.go
- utils/yaml.go
---
For Author:
---
For Reviewer:
---
> fix: Update rly path data instead of re-create

- cmd/migrate/v_0_1_12.go
- data_layer/damock/damock.go
---
For Author:
---
For Reviewer:
---
> fix: Migrate panic when using mock DA

- README.md
---
For Author:
---
For Reviewer:
---
> chore: Removed unnecessary info for roller users from readme

- cmd/config/set/set.go
---
For Author:
---
For Reviewer:
---
> chore: Update `roller config set --help` to show the supported keys

- data_layer/avail/avail.go
---
For Author:
---
For Reviewer:
---
> chore: Change avail status to `active`

- cmd/config/init/flags.go
- cmd/da-light-client/start/start.go
- cmd/migrate/migrate.go
- cmd/relayer/start/start.go
- cmd/run/run.go
- cmd/sequencer/start/start.go
- cmd/utils/error_handling.go
- version/version.go
---
For Author:
---
For Reviewer:
---
> chore: Instruct users to run `roller migrate` 

- relayer/create_ibc_channel.go
---
For Author:
---
For Reviewer:
---
> chore: Make relayer rollapp hub height log clear

- cmd/config/export/export.go
---
For Author:
---
For Reviewer:
---
> chore: Change analytics to true in `roller config export`

- cmd/config/init/flags.go
- cmd/config/init/init.go
- cmd/config/init/interactive.go
- cmd/config/init/unique_rollapp_id.go
- config/chainid.go
- config/config.go
From now on Roller will generate the EIP155 ID for both EVM & non EVM rollapps for hub uniqueness & standardization.
---
For Author:
---
For Reviewer:
---
> feat: Auto-generate EIP115 and revision

- cmd/config/init/flags.go
- cmd/config/init/init.go
- cmd/config/init/interactive.go
---
For Author:
---
For Reviewer:
---
> chore: Rollapp ID should consist only of alphabetical lowercase english letters

- sequencer/config.go
---
For Author:
---
For Reviewer:
---
> chore: Update rollapp config for better stability

- cmd/config/init/flags.go
- cmd/config/init/init.go
- test/config/init/init_test.go
…llapps
---
For Author:
---
For Reviewer:
---
> fix: Generate formatted rollapp id for local rollapps

- cmd/config/export/export.go
- cmd/config/export/types.go
---
For Author:
---
For Reviewer:
---
> chore: Add an empty description and website to config export

- cmd/config/init/flags.go
- cmd/config/init/init.go
- cmd/config/init/interactive.go
when initiailizng a rollapp, the default config is read from the existing rollapp config
---
For Author:
---
For Reviewer:
---
> feat: using flags as defualts in interactive mode

- cmd/config/export/export.go
- cmd/config/init/consts.go
- cmd/config/init/flags.go
- cmd/config/init/init.go
- cmd/config/init/interactive.go
- cmd/consts/consts.go
---
For Author:
---
For Reviewer:
---
> fix: Match `roller config export` faucet URL with hub ID

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: Update rollapp evm

- cmd/utils/bash_commands.go
---
For Author:
---
For Reviewer:
---
> chore: Add verbose logs for periodic commands

- cmd/config/export/types.go
---
For Author:
---
For Reviewer:
---
> chore: Change isValidator to validator in export json

- cmd/utils/bash_commands.go
---
For Author:
---
For Reviewer:
---
> fix: Return relayer logs for periodic commands

- .github/workflows/build.yml
- cmd/consts/consts.go
- cmd/tx/claim/claim.go
- cmd/tx/tx.go
- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> feat: Add a `claim-rewards` command

- cmd/config/init/keys.go
- cmd/consts/consts.go
> fix: typos

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: update compile_locally.sh to include latest relayer version

- .github/workflows/build.yml
- cmd/config/init/consts.go
- cmd/config/init/init.go
- cmd/config/init/keys.go
- cmd/consts/consts.go
- cmd/migrate/migrate.go
- cmd/migrate/v0_1_18.go
- cmd/tx/claim/claim.go
- cmd/tx/tx.go
- compile_locally.sh
- config/config.go
- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> chore: Get latest fixes from main

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> fix: update compile_locally.sh with relayer version v0.1.6

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> fix: cherry picked a relayer fix 

- cmd/config/init/init.go
- config/config.go
- test/config/init/init_test.go
---
For Author:
---
For Reviewer:
---
> chore: Enforce token supply

- .github/workflows/build.yml
---
For Author:
---
For Reviewer:
---
> chore: update celestia version to latest patch

- cmd/utils/bash_commands.go
---
For Author:
---
For Reviewer:
---
> chore: Improve error message when `stderr` is empty

- .github/workflows/build.yml
- cmd/config/init/relayer.go
- cmd/tx/register/bash_commands.go
- cmd/utils/bash_commands.go
---
For Author:
---
For Reviewer:
---
> feat: add denom registration on rollapp creation

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: update compile_locally rollapp-evm version

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: update compile_locally rollapp-evm version (#634)

- .github/pull_request_template.md
---
For Author:
---
For Reviewer:
---
> chore: Fix missing word in PR template and make caps consistent

- cmd/tx/register/register.go
- cmd/tx/tx_utils/tx_utils.go
---
For Author:
---
For Reviewer:
---
> fix: Make register return an error on insufficient funds

- .github/workflows/build.yml
- README.md
- compile_locally.sh
Reverts dymensionxyz/roller#648
> chore: revert Add install binaries instruction to Readme testing section

- data_layer/avail/avail.go
---
For Author:
---
For Reviewer:
---
> chore: updated avail endpoint to point to goldberg testnet

- compile_locally.sh
---
For Author:
---
For Reviewer:
---
> chore: changed compile locally to use go 1.20

- cmd/config/init/consts.go
- cmd/consts/consts.go
---
For Author:
---
For Reviewer:
---
> chore: updated gas price of hub for 20b

- data_layer/avail/avail.go
> changed var name from `DeafultRPCEndpoint` to `DefaultRPCEndpoint`

- README.md
---
For Author:
---
For Reviewer:
---
> chore: remove typo

- cmd/config/init/genesis.go
- cmd/consts/consts.go
- cmd/tx/register/bash_commands.go
- cmd/tx/register/register.go
- config/config.go
---
For Author:
---
For Reviewer:
---
> feat: support sequencer bond for registration

- relayer/commands.go
The added flags aim to improve relayer performance. I created a separate issue to implement a better solution #769 
---
For Author:
---
For Reviewer:
---
> chore: update rly start command with flags that improve the relayer performance

- .github/workflows/test.yml
- cmd/config/init/genesis.go
- cmd/config/init/rollapp.go
- compile_locally.sh
- go.mod
- test/config/init/goldens/init_with_flags/rollapp/config/genesis.json
- test/config/init/goldens/init_without_flags/rollapp/config/genesis.json
---
For Author:
---
For Reviewer:
---
> fix: roller initialization

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/markdownlint.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yml
- .golangci.yml
- .goreleaser.yaml
- .pre-commit-config.yaml
- go.mod
---
For Author:
---
For Reviewer:
---
> chore: add goimports reviser pre commit hook

- cmd/config/export/export.go
- cmd/config/init/flags.go
- cmd/consts/consts.go
---
For Author:
---
For Reviewer:
---
> chore: update hub info

- cmd/config/init/flags.go
- cmd/config/init/genesis.go
- cmd/config/init/keys.go
- cmd/config/init/rollapp.go
- cmd/config/show/show.go
- cmd/da-light-client/start/start.go
- cmd/keys/export/export.go
- cmd/relayer/relayer.go
- cmd/relayer/start/start.go
- cmd/relayer/status/status.go
- cmd/rollapp/init/main.go
- cmd/run/services_status.go
- cmd/services/services.go
- cmd/utils/log.go
- data_layer/avail/avail.go
- sequencer/config.go
- utils/archives/archives.go
---
For Author:
---
For Reviewer:
---
> fix: config files

- cmd/rollapp/rollapp.go
- cmd/rollapp/status/status.go
- sequencer/config.go
- sequencer/status.go
close #798 
---
For Author:
---
For Reviewer:
---
> feat: add rollapp status command

- cmd/config/init/genesis.go
- cmd/config/init/local_hub.go
- cmd/keys/keys.go
- cmd/rollapp/start/start.go
---
For Author:
---
For Reviewer:
---
> fix: add genesis account to genesis file

- cmd/config/init/format.go
- cmd/config/init/keys.go
- cmd/config/init/output.go
- cmd/rollapp/init/utils.go
- cmd/utils/keys.go
---
For Author:
---
For Reviewer:
---
> chore: improve init output

- cmd/config/export/export.go
- cmd/config/init/genesis.go
- cmd/config/init/keys.go
- cmd/config/init/output.go
- cmd/config/init/relayer.go
- cmd/consts/consts.go
- cmd/relayer/relayer.go
- cmd/relayer/run/run.go
- cmd/rollapp/init/main.go
- cmd/rollapp/init/utils.go
- cmd/run/run.go
- cmd/tx/fund_faucet/fund_faucet.go
- cmd/utils/bash_commands.go
- cmd/utils/error_handling.go
- cmd/utils/key_info.go
- cmd/utils/keys.go
- cmd/utils/output.go
- config/config.go
- relayer/channels.go
- relayer/config.go
- relayer/connections.go
- relayer/create_ibc_channel.go
- relayer/query.go
- relayer/relayer_manager.go
- sequencer/config.go
- sequencer/sequencer_manager.go
- utils/filesystem.go
---
For Author:
---
For Reviewer:
---
> feat: run relayer using roller

- cmd/config/init/genesis.go
- cmd/rollapp/init/main.go
- scripts/install-binaries.sh
---
For Author:
---
For Reviewer:
---
> chore: add bin install script

- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/run/run.go
- utils/rollapp/rollapp.go
- utils/sequencer/sequencer.go
chore: move GetRegisteredSequencers to sequencer package
fix: load rollapp id from roller config during run
chore: update rollapp_id during init
---
For Author:
---
For Reviewer:
---
> fix: check whether rollapp exists during initialization

- cmd/da-light-client/start/start.go
- cmd/relayer/run/run.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/rollapp.go
- cmd/rollapp/run/run.go
- cmd/services/load/load.go
- cmd/services/services.go
- cmd/services/start/start.go
- data_layer/celestia/celestia.go
- go.mod
- go.sum
- utils/bash/bash_commands.go
- utils/config/config.go
- utils/config/tomlconfig/toml.go
- utils/rollapp/rollapp.go
- utils/rollapp/types.go
- utils/sequencer/sequencer.go
- utils/service_manager/service.go
- utils/tx/tx.go
---
For Author:
---
For Reviewer:
---
> feat: finalize sequencer registration flow

- cmd/config/init/output.go
- cmd/consts/consts.go
- cmd/consts/da.go
- cmd/consts/dymension.go
- cmd/consts/types.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/run/run.go
- data_layer/celestia/celestia.go
- utils/sequencer/sequencer.go
- utils/toml.go
---
For Author:
---
For Reviewer:
---
> feat: celestia light client config logic, sync from da head for first sequencer, sync from first state update for others

- cmd/config/init/genesis.go
- cmd/config/init/rollapp.go
- cmd/da-light-client/start/start.go
- cmd/relayer/relayer.go
- cmd/relayer/run/run.go
- cmd/relayer/start/start.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/run/run.go
- cmd/root.go
- cmd/services/load/load.go
- cmd/services/start/start.go
- cmd/utils/balance.go
- data_layer/celestia/celestia.go
- go.sum
- relayer/channels.go
- relayer/connections.go
- sequencer/config.go
- test/config/init/testutils/rollapp.go
- utils/bash/bash_commands.go
- utils/config/config.go
- utils/config/tomlconfig/toml.go
- utils/dymint/dymint.go
- utils/genesis/genesis.go
- utils/relayer/relayer.go
- utils/rollapp/rollapp.go
- utils/rollapp/types.go
---
For Author:
---
For Reviewer:
---
> feat: finalize relayer flow

- utils/genesis/genesis.go
---
For Author:
---
For Reviewer:
---
> chore: return an err if genesis url field is not populated

- cmd/consts/consts.go
- cmd/eibc/init.go
- cmd/eibc/start.go
---
For Author:
---
For Reviewer:
---
> fix: eibc client command error handling

- cmd/consts/dymension.go
- cmd/rollapp/init/init.go
---
For Author:
---
For Reviewer:
---
> chore: add playground

- cmd/eibc/scale.go
- cmd/relayer/run/run.go
- cmd/relayer/start/start.go
- cmd/rollapp/init/init.go
- cmd/rollapp/rollapp.go
- cmd/rollapp/run/run.go
- cmd/rollapp/start/start.go
- cmd/root.go
- cmd/services/services.go
---
For Author:
---
For Reviewer:
---
> chore: improve command descriptions

- cmd/rollapp/rollapp.go
- cmd/rollapp/sequencer/metadata/export/export.go
- cmd/rollapp/sequencer/metadata/metadata.go
- cmd/rollapp/sequencer/metadata/update/update.go
- cmd/rollapp/sequencer/sequencer.go
- cmd/services/services.go
- utils/sequencer/sequencer.go
- utils/sequencer/types.go
- utils/structs/struct.go
---
For Author:
---
For Reviewer:
---
> feat: add commands to export and update sequencer metadata

- cmd/da-light-client/start/start.go
- utils/config/config.go
- utils/service_manager/service.go
---
For Author:
---
For Reviewer:
---
> chore: fix some comments

- cmd/config/init/rollapp.go
- cmd/rollapp/init/utils.go
---
For Author:
---
For Reviewer:
---
> fix: handle empty genesis token supply

- cmd/consts/consts.go
---
For Author:
---
For Reviewer:
---
> chore: update the default fee to be 2 dym to cover submission

- cmd/config/init/genesis.go
- cmd/config/init/keys.go
- cmd/eibc/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/start/start.go
- utils/config/tomlconfig/toml.go
---
For Author:
---
For Reviewer:
---
> fix: cleanup unnecessary wallets, improve command output

- cmd/rollapp/run/run.go
- utils/sequencer/sequencer.go
fix: use the provided bond amount during registration
---
For Author:
---
For Reviewer:
---
> fix: query against a node when fetching bond params

- cmd/rollapp/init/utils.go
- cmd/rollapp/run/run.go
- cmd/rollapp/sequencer/metadata/update/update.go
- sequencer/status.go
- utils/genesis/genesis.go
- utils/rollapp/rollapp.go
- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> fix: use a chain ID from the available metadata

- cmd/relayer/run/run.go
- relayer/create_ibc_channel.go
- utils/dymint/dymint.go
---
For Author:
---
For Reviewer:
---
> fix(relayer run): wait for rollapp to be healthy after block time change

- cmd/config/export/export.go
- cmd/config/init/flags.go
- cmd/config/init/format.go
- cmd/config/set/da.go
- cmd/config/set/lc_rpc.go
- cmd/consts/da.go
- cmd/consts/types.go
- cmd/da-light-client/start/start.go
- cmd/keys/export/export.go
- cmd/keys/list/list.go
- cmd/migrate/v1_0_05.go
- cmd/migrate/v_0_1_12.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/run/run.go
- cmd/rollapp/sequencer/metadata/update/update.go
- cmd/run/run.go
- cmd/run/services_info.go
- data_layer/celestia/celestia.go
- sequencer/config.go
- utils/config/config.go
- utils/config/tomlconfig/toml.go
---
For Author:
---
For Reviewer:
---
> feat: fetch DA information from `roller.toml` for easy endpoint changes

- scripts/install-binaries.sh
---
For Author:
---
For Reviewer:
---
> refactor: binary installation script to update versions

- cmd/config/init/genesis.go
- cmd/consts/consts.go
- cmd/consts/da.go
- cmd/da-light-client/da_light_client.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/run/run.go
- cmd/rollapp/sequencer/metadata/export/export.go
- cmd/rollapp/sequencer/metadata/update/update.go
- cmd/rollapp/sequencer/rewards/rewards.go
- cmd/rollapp/sequencer/sequencer.go
- cmd/root.go
- cmd/tx/claim/claim.go
- cmd/utils/fetch_accounts_data.go
- cmd/utils/key_info.go
- cmd/version/version.go
- data_layer/avail/utils.go
- go.mod
- go.sum
- scripts/install-binaries.sh
- utils/bash/bash_commands.go
- utils/relayer/relayer.go
- utils/rollapp/types.go
- utils/sequencer/sequencer.go
- utils/tx/tx.go
---
For Author:
---
For Reviewer:
---
> feat: handle sequencer reward address

- .pre-commit-config.yaml
- cmd/relayer/run/run.go
- go.mod
- relayer/create_ibc_channel.go
- utils/eibc/eibc.go
---
For Author:
---
For Reviewer:
---
> fix: relayer client creation flow

- cmd/rollapp/init/init.go
- cmd/rollapp/run/run.go
- cmd/root.go
- utils/rollapp/bechprefix.go
---
For Author:
---
For Reviewer:
---
> fix: verify rollapp bech prefix against the build flag

- cmd/consts/consts.go
- cmd/eibc/fulfill/order/order.go
- utils/eibc/eibc.go
---
For Author:
---
For Reviewer:
---
> chore: update eibc fulfill

- cmd/relayer/run/run.go
- cmd/root.go
- go.mod
- utils/config/yamlconfig/yaml.go
- utils/eibc/eibc.go
---
For Author:
---
For Reviewer:
---
> chore: add the missing imports

- relayer/commands.go
---
For Author:
---
For Reviewer:
---
> fix: update relayer start cmd

- cmd/binaries/install/install.go
---
For Author:
---
For Reviewer:
---
> fix: install roller as part of binary installation

- cmd/config/set/hub_rpc.go
- cmd/config/set/set.go
- cmd/migrate/migrate.go
- cmd/migrate/v_0_1_12.go
- cmd/relayer/start/start.go
close #888 
---
For Author:
---
For Reviewer:
---
> fix: show relayer log location

- cmd/binaries/install/install.go
- cmd/consts/consts.go
- cmd/relayer/run/run.go
- cmd/rollapp/init/init.go
- cmd/rollapp/run/run.go
- cmd/rollapp/sequencer/rewards/rewards.go
- go.mod
- go.sum
- scripts/install-binaries.sh
- utils/config/tomlconfig/toml.go
- utils/genesis/genesis.go
- utils/rollapp/rollapp.go
- utils/rollapp/types.go
close #891 
---
For Author:
---
For Reviewer:
---
> chore: update to latest dymension 

- cmd/binaries/install/install.go
- cmd/relayer/run/run.go
- relayer/create_ibc_channel.go
- sequencer/sequencer_manager.go
---
For Author:
---
For Reviewer:
---
> chore: relayer updates

- cmd/binaries/install/install.go
- cmd/consts/consts.go
- cmd/eibc/fulfill/denoms/set/set.go
- cmd/eibc/fulfill/rollapps/set/set.go
- cmd/eibc/init/init.go
- cmd/relayer/run/run.go
- cmd/relayer/status/status.go
- cmd/rollapp/rollapp.go
- cmd/rollapp/run/run.go
- cmd/services/start/start.go
- relayer/create_ibc_channel.go
- relayer/relayer_manager.go
- utils/config/yamlconfig/yaml.go
- utils/yaml.go
---
For Author:
---
For Reviewer:
---
> chore: fix known issues

- cmd/binaries/install/install.go
- cmd/eibc/init/init.go
- cmd/relayer/start/start.go
- cmd/services/stop/stop.go
- utils/archives/archives.go
- utils/bash/bash_commands.go
- utils/dependencies/types.go
---
For Author:
---
For Reviewer:
---
> refactor: installation

- cmd/binaries/install/install.go
- cmd/relayer/run/run.go
- cmd/rollapp/run/run.go
- utils/bash/bash_commands.go
---
For Author:
---
For Reviewer:
---
> chore: ux improvements

- cmd/binaries/install/install.go
- cmd/relayer/run/run.go
- cmd/relayer/status/status.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/run/run.go
- cmd/services/start/start.go
- cmd/services/stop/stop.go
- utils/bash/bash_commands.go
close #864 
---
For Author:
---
For Reviewer:
---
> fix: remove systemd services on reset

- cmd/consts/consts.go
- cmd/relayer/run/run.go
- cmd/rollapp/init/init.go
- cmd/rollapp/run/run.go
- cmd/services/start/start.go
- utils/dymint/dymint.go
- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> chore: fix feedback from 20240910

- cmd/binaries/binaries.go
- cmd/binaries/install/install.go
- cmd/rollapp/init/init.go
- cmd/root.go
---
For Author:
---
For Reviewer:
---
> chore: move dependency installation to `init` command

- cmd/relayer/relayer.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/rollapp.go
- cmd/rollapp/setup/setup.go
---
For Author:
---
For Reviewer:
---
> chore: rename `run` to `setup`

- cmd/relayer/setup/setup.go
- cmd/rollapp/init/init.go
- cmd/rollapp/sequencer/metadata/update/update.go
- cmd/rollapp/setup/setup.go
- cmd/services/start/start.go
- utils/sequencer/sequencer.go
chore: update setup to run in next steps
---
For Author:
---
For Reviewer:
---
> feat: display and accept bond amount in base denom

- cmd/rollapp/init/init.go
- cmd/rollapp/setup/setup.go
- cmd/rollapp/start/start.go
- data_layer/celestia/celestia.go
---
For Author:
---
For Reviewer:
---
> feat: add `--mock` flag to init

- .github/workflows/release.yaml
- .goreleaser.yaml
- Makefile
- install.sh
ci: align goreleaser config
---
For Author:
---
For Reviewer:
---
> refactor: add install script

- Makefile
---
For Author:
---
For Reviewer:
---
> chore: add release commands to Makefile

- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/markdownlint.yaml
- .github/workflows/test.yml
- cmd/rollapp/init/init.go
- go.mod
- go.sum
- utils/bash/bash_commands.go
- utils/genesis/genesis.go
- utils/rollapp/rollappId.go
- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> feat: validate rollapp ID before dependency installation

- cmd/rollapp/setup/setup.go
- utils/sequencer/types.go
- utils/structs/struct.go
close #904 
---
For Author:
---
For Reviewer:
---
> feat: make it possible to fill out the moniker and social media links for sequencer

- cmd/rollapp/init/init.go
---
For Author:
---
For Reviewer:
---
> chore: update dym version

- README.md
- cmd/binaries/binaries.go
- cmd/binaries/install/install.go
- cmd/rollapp/init/init.go
- cmd/rollapp/sequencer/metadata/update/update.go
- cmd/rollapp/setup/setup.go
- cmd/root.go
- cmd/tx/fund_faucet/fund_faucet.go
- cmd/tx/tx_utils/tx_utils.go
- utils/archives/archives.go
- utils/bash/bash_commands.go
- utils/dependencies/dependencies.go
- utils/dependencies/types/types.go
close #900 
---
For Author:
---
For Reviewer:
---
> fix: handle `raw_log` error during transaction execution

- cmd/relayer/setup/setup.go
---
For Author:
---
For Reviewer:
---
> fix: remove trust-period override in relayer config

- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- utils/dependencies/dependencies.go
---
For Author:
---
For Reviewer:
---
> chore: update dependencies for new relayer version

- utils/bash/bash_commands.go
- utils/dependencies/dependencies.go
---
For Author:
---
For Reviewer:
---
> fix: change library installation flow

- cmd/config/init/flags.go
- cmd/config/set/da.go
- cmd/eibc/fulfill/denoms/list/list.go
- cmd/eibc/fulfill/denoms/remove/remove.go
- cmd/eibc/fulfill/denoms/set/set.go
- cmd/eibc/fulfill/order/order.go
- cmd/eibc/fulfill/rollapps/list/list.go
- cmd/eibc/fulfill/rollapps/remove/remove.go
- cmd/eibc/fulfill/rollapps/set/set.go
- cmd/eibc/init/init.go
- cmd/eibc/start/start.go
- cmd/migrate/v_0_1_12.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/init/mockbackends.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/sequencer/metadata/export/export.go
- cmd/rollapp/sequencer/metadata/update/update.go
- cmd/rollapp/sequencer/rewards/rewards.go
- cmd/rollapp/setup/setup.go
- cmd/rollapp/start/start.go
- relayer/create_ibc_channel.go
- relayer/query.go
- utils/dependencies/dependencies.go
- utils/filesystem/filesystem.go
- utils/genesis/genesis.go
- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> fix: relayer ibc creation

- cmd/rollapp/setup/setup.go
- utils/rollapp/rollappId.go
- utils/sequencer/sequencer.go
close #937 
- show bond in denom
---
For Author:
---
For Reviewer:
---
> fix(ux): remove irrelevant prompts 

- cmd/eibc/eibc.go
- cmd/relayer/relayer.go
- cmd/rollapp/rollapp.go
- cmd/rollapp/setup/setup.go
- cmd/services/logs/logs.go
- cmd/services/services.go
- go.mod
- utils/filesystem/filesystem.go
- utils/rollapp/rollappId.go
- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> feat: add logs command for services

- cmd/relayer/setup/setup.go
- cmd/relayer/start/start.go
- relayer/create_ibc_channel.go
- utils/dymint/dymint.go
close #905 
close #939 
---
For Author:
---
For Reviewer:
---
> fix: relayer setup output should show the channels

- cmd/rollapp/start/start.go
- cmd/rollapp/status/status.go
- cmd/services/start/start.go
- sequencer/status.go
- utils/sequencer/sequencer.go
- utils/service_manager/service.go
---
For Author:
---
For Reviewer:
---
> feat: add sequencer address and balance to `rollapp` output commands

- cmd/binaries/install/install.go
- cmd/rollapp/init/init.go
- cmd/services/load/load.go
- cmd/services/restart/restart.go
- cmd/services/start/start.go
- utils/service_manager/service.go
---
For Author:
---
For Reviewer:
---
> feat: add launchctl service support for macos

- cmd/config/init/keys.go
- cmd/consts/consts.go
- cmd/da-light-client/start/start.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/start/start.go
- cmd/services/load/load.go
- cmd/services/start/start.go
- cmd/services/stop/stop.go
- cmd/utils/key_info.go
- utils/bash/bash_commands.go
- utils/config/config.go
- utils/config/tomlconfig/toml.go
- utils/dymint/dymint.go
- utils/service_manager/service.go
fix: services commands for darwin
fix: relayer should only show hub address for funding
---
For Author:
---
For Reviewer:
---
> fix: relayer setup flow for darwin

- cmd/services/load/load.go
- utils/config/cronjobs/cronjobs.go
feat: cron
---
For Author:
---
For Reviewer:
---
> feat: add cron job for relayer flush

- .goreleaser.yaml
- cmd/eibc/fulfill/order/order.go
- cmd/eibc/fulfill/rollapps/rollapps.go
- cmd/rollapp/start/start.go
- cmd/rollapp/status/status.go
- cmd/services/load/load.go
- cmd/tx/fund_faucet/fund_faucet.go
- sequencer/sequencer_manager.go
- utils/dymint/dymint.go
---
For Author:
---
For Reviewer:
---
> fix(ux): update prompts and `rollapp status` command

- cmd/consts/dymension.go
---
For Author:
---
For Reviewer:
---
> fix(hub): update playground hub chain id

- cmd/relayer/setup/setup.go
- cmd/rollapp/setup/setup.go
- cmd/services/start/start.go
- cmd/utils/output.go
- go.mod
- go.sum
- utils/dependencies/dependencies.go
---
For Author:
---
For Reviewer:
---
> feat: add progress bar to downloads

- cmd/rollapp/setup/setup.go
- utils/dymint/dymint.go
---
For Author:
---
For Reviewer:
---
> fix: set max proof time to 1m

- cmd/binaries/install/install.go
- cmd/consts/consts.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/setup/setup.go
- cmd/rollapp/start/start.go
- utils/config/tomlconfig/toml.go
- utils/dependencies/dependencies.go
- utils/dymint/dymint.go
- utils/rollapp/bechprefix.go
---
For Author:
---
For Reviewer:
---
> feat: add wasm rollapp support

- cmd/eibc/init/init.go
- utils/dependencies/dependencies.go
---
For Author:
---
For Reviewer:
---
> fix(deps): bump eibc version

- cmd/eibc/fulfill/denoms/remove/remove.go
- cmd/eibc/fulfill/denoms/set/set.go
- cmd/eibc/fulfill/order/order.go
- cmd/eibc/fulfill/rollapps/remove/remove.go
- cmd/eibc/fulfill/rollapps/set/set.go
- cmd/root.go
- cmd/services/start/start.go
- cmd/utils/key_info.go
- utils/eibc/eibc.go
- utils/eibc/types.go
- utils/keys/keys.go
---
For Author:
---
For Reviewer:
---
> fix: eibc client commands

- cmd/config/export/bech32.go
- cmd/eibc/fulfill/order/order.go
- cmd/keys/list/list.go
- cmd/rollapp/sequencer/metadata/export/export.go
- cmd/rollapp/setup/setup.go
- cmd/utils/key_info.go
- utils/eibc/eibc.go
---
For Author:
---
For Reviewer:
---
> fix(keys): align key retrieval function with key creation

- cmd/block-explorer/run/run.go
- cmd/block-explorer/run/utils.go
- cmd/consts/consts.go
- utils/blockexplorer/blockexplorer.go
- utils/database/postgresql/utils.go
- utils/dependencies/dependencies.go
- utils/dependencies/types/types.go
- utils/docker/docker.go
- utils/filesystem/filesystem.go
---
For Author:
---
For Reviewer:
---
> fix(block-explorer): make the block-explorer creation more reliable

- cmd/block-explorer/block-explorer.go
- cmd/block-explorer/run/run.go
- cmd/block-explorer/teardown/teardown.go
---
For Author:
---
For Reviewer:
---
> feat(block-explorer): add a command to tear down the block explorer setup

- cmd/rollapp/setup/setup.go
---
For Author:
---
For Reviewer:
---
> fix(da): don't ask to override the existing da config

- install.sh
---
For Author:
---
For Reviewer:
---
> chore(scripts): add version to roller installation script

- cmd/consts/consts.go
- cmd/consts/da.go
- cmd/consts/types.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/sequencer/metadata/export/export.go
- cmd/rollapp/setup/setup.go
- cmd/rollapp/start/start.go
- data_layer/celestia/celestia.go
- utils/config/config.go
- utils/config/tomlconfig/toml.go
- utils/dependencies/dependencies.go
- utils/filesystem/filesystem.go
- utils/genesis/genesis.go
- utils/rollapp/bechprefix.go
- utils/rollapp/rollappId.go
---
For Author:
---
For Reviewer:
---
> fix: retrieve da backend from genesis rollappparams

- cmd/binaries/install/install.go
- cmd/config/init/rollapp.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- utils/config/tomlconfig/toml.go
- utils/dependencies/dependencies.go
- utils/filesystem/filesystem.go
- utils/genesis/genesis.go
- utils/rollapp/rollappId.go
- utils/service_manager/service.go
---
For Author:
---
For Reviewer:
---
> fix: retrieve rollapp binary commit from genesis

- cmd/rollapp/init/init.go
- utils/dependencies/dependencies.go
---
For Author:
---
For Reviewer:
---
> fix(mock): install only rollapp binary for mock

- cmd/block-explorer/run/run.go
- cmd/block-explorer/run/utils.go
- utils/filesystem/filesystem.go
---
For Author:
---
For Reviewer:
---
> feat: run block explorer against any endpoint

- cmd/relayer/setup/setup.go
- cmd/relayer/start/start.go
---
For Author:
---
For Reviewer:
---
> chore: remove deprecated relayer warning messages

- cmd/relayer/setup/setup.go
- relayer/create_ibc_channel.go
---
For Author:
---
For Reviewer:
---
> fix: wait for valid ra height relayer setup

- cmd/relayer/setup/setup.go
- cmd/rollapp/start/start.go
- cmd/services/logs/logs.go
- relayer/create_ibc_channel.go
- sequencer/sequencer_manager.go
- utils/filesystem/filesystem.go
close #959 
---
For Author:
---
For Reviewer:
---
> chore: `rollapp start` should have configurable log level

- .github/workflows/release.yaml
- cmd/eibc/init/init.go
- cmd/eibc/start/start.go
- utils/dependencies/dependencies.go
close #985 
---
For Author:
---
For Reviewer:
---
> fix: require user to run `eibc init` before `start`

- cmd/eibc/init/init.go
- utils/config/tomlconfig/toml.go
- utils/rollapp/rollapp.go
- utils/sequencer/sequencer.go
close #986 
---
For Author:
---
For Reviewer:
---
> fix: eibc client should not rely on roller config

- cmd/eibc/init/init.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/config/set/set.go
- cmd/rollapp/init/init.go
- cmd/rollapp/sequencer/metadata/export/export.go
- cmd/rollapp/setup/setup.go
- cmd/services/load/load.go
- cmd/services/start/start.go
close #991 
---
For Author:
---
For Reviewer:
---
> fix: all "next steps" messages should be last

- cmd/rollapp/start/start.go
---
For Author:
---
For Reviewer:
---
> fix: show da balance in status

- cmd/rollapp/setup/setup.go
- utils/sequencer/sequencer.go
close #844 
---
For Author:
---
For Reviewer:
---
> fix: handle the initial sequencer

- cmd/config/export/export.go
- cmd/config/init/keys.go
---
For Author:
---
For Reviewer:
---
> fix: coin type should be 60 for all keys

- cmd/config/export/export.go
- cmd/config/init/keys.go
---
For Author:
---
For Reviewer:
---
> fix: set cointype to 118 for wasm rollapp

- .github/ISSUE_TEMPLATE/bug-report.yaml
- cmd/config/config.go
- cmd/config/export/export.go
- cmd/config/init/keys.go
- cmd/consts/da.go
- cmd/consts/types.go
- cmd/eibc/fulfill/rollapps/list/list.go
- cmd/eibc/funds/funds.go
- cmd/relayer/setup/setup.go
- cmd/relayer/start/start.go
- cmd/relayer/status/status.go
- cmd/tx/fund_faucet/fund_faucet.go
- cmd/tx/tx.go
- cmd/utils/log.go
- relayer/channels.go
- relayer/connections.go
- relayer/create_ibc_channel.go
- relayer/relayer_manager.go
- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> feat: it should be possible to run relayer for any rollapp when there's an active IBC connection

- cmd/consts/types.go
- cmd/da-light-client/start/start.go
- cmd/relayer/setup/setup.go
- cmd/relayer/start/start.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/sequencer/metadata/export/export.go
- cmd/rollapp/setup/setup.go
- cmd/utils/output.go
- relayer/channels.go
- relayer/config/config.yaml
- relayer/connections.go
- relayer/create_ibc_channel.go
- relayer/query.go
- utils/config/config.go
- utils/config/tomlconfig/toml.go
close #856 
---
For Author:
---
For Reviewer:
---
> fix: relayer `setup` and `start` commands should handle metadata from chain

- cmd/config/init/keys.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/setup/setup.go
- cmd/utils/keys.go
- utils/config/tomlconfig/toml.go
- utils/keys/keys.go
---
For Author:
---
For Reviewer:
---
> feat: it should be possible to import an existing `hub_sequencer` key

- cmd/rollapp/init/utils.go
- cmd/rollapp/setup/setup.go
- sequencer/utils.go
---
For Author:
---
For Reviewer:
---
> feat: add support for different full node types (rpc and archive)

- cmd/observability/export/export.go
- cmd/observability/export/templates/grafana/dashboard.json
- cmd/observability/observability.go
- cmd/root.go
- go.mod
- go.sum
---
For Author:
---
For Reviewer:
---
> feat: add cmd to export a grafana dashboard with vital metrics

- cmd/eibc/fulfill/rollapps/set/set.go
- cmd/eibc/init/init.go
- utils/eibc/eibc.go
---
For Author:
---
For Reviewer:
---
> feat(eibc): prompts user for fee percentage for the rollapp upon init

- README.md
---
For Author:
---
For Reviewer:
---
> fix(doc): updated docs link in readme

- cmd/consts/da.go
- cmd/consts/types.go
- cmd/da-light-client/start/start.go
- cmd/query/query.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/start/start.go
- cmd/rollapp/status/status.go
- cmd/root.go
- cmd/services/load/load.go
- cmd/services/restart/restart.go
- data_layer/celestia/celestia.go
- go.mod
- go.sum
- utils/config/tomlconfig/toml.go
- utils/dymint/dymint.go
- utils/healthagent/healthagent.go
close #1018 
---
For Author:
---
For Reviewer:
---
> feat: add health agent for hotswapping unhealthy da node

- cmd/relayer/setup/setup.go
- cmd/rollapp/init/init.go
- cmd/rollapp/setup/setup.go
- cmd/services/load/load.go
- cmd/services/restart/restart.go
- cmd/services/start/start.go
- relayer/channels.go
- relayer/connections.go
- utils/dependencies/dependencies.go
- utils/keys/balances.go
- utils/migrations/migrations.go
- utils/rollapp/bechprefix.go
- utils/rollapp/rollappId.go
---
For Author:
---
For Reviewer:
---
> fix: relayer setup flow for new and existing ibc channels

- cmd/relayer/start/start.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- utils/rollapp/rollapp.go
---
For Author:
---
For Reviewer:
---
> fix: improve custom env support for rollapp and relayer

- cmd/da-light-client/start/start.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/start/start.go
- cmd/rollapp/status/status.go
- utils/dependencies/dependencies.go
- utils/dymint/dymint.go
- utils/rollapp/rollapp.go
---
For Author:
---
For Reviewer:
---
> fix: dont require da funding for full nodes

- cmd/config/init/relayer.go
- cmd/relayer/setup/setup.go
- cmd/relayer/start/start.go
- cmd/rollapp/init/init.go
- relayer/channels.go
- relayer/create_ibc_channel.go
- utils/config/config.go
- utils/dependencies/dependencies.go
- utils/rollapp/rollapp.go
---
For Author:
---
For Reviewer:
---
> fix: relayer setup should create keys on remote hosts

- cmd/relayer/setup/setup.go
- cmd/relayer/start/start.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/sequencer/metadata/export/export.go
- cmd/rollapp/sequencer/rewards/rewards.go
- cmd/rollapp/setup/setup.go
- data_layer/da_layer.go
- relayer/channels.go
- utils/config/config.go
- utils/config/propmts.go
- utils/config/tomlconfig/toml.go
- utils/config/types.go
- utils/dependencies/dependencies.go
- utils/dependencies/dymd.go
- utils/genesis/genesis.go
- utils/keys/keys.go
- utils/keys/sequencer.go
- utils/rollapp/rollapp.go
- utils/roller/config.go
- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> refactor: decouple code for better readability and testability

- cmd/rollapp/init/init.go
- data_layer/celestia/celestia.go
- utils/bash/bash_commands.go
- utils/config/config.go
- utils/filesystem/filesystem.go
- utils/filesystem/types.go
- utils/keys/key_config.go
- utils/sequencer/sequencer.go
- utils/sequencer/types.go
---
For Author:
---
For Reviewer:
---
> feat: add sequencer address checks upon init

- cmd/rollapp/sequencer/bond/decrease/decrease.go
- cmd/rollapp/sequencer/bond/increase/increase.go
- cmd/rollapp/sequencer/metadata/update/update.go
---
For Author:
---
For Reviewer:
---
> fix: apply os keyring patches

- utils/structs/struct.go
---
For Author:
---
For Reviewer:
---
> fix: create dir during struct export

- cmd/consts/consts.go
- cmd/consts/dymension.go
- cmd/eibc/fulfill/rollapps/set/set.go
- cmd/eibc/init/init.go
- cmd/eibc/init/templates/members.json.tmpl
- cmd/eibc/init/templates/policy.json.tmpl
- cmd/observability/export/templates/grafana/dashboard.json
- cmd/rollapp/setup/setup.go
- cmd/tx/claim/claim.go
- data_layer/avail/avail.go
- data_layer/celestia/celestia.go
- sequencer/sequencer_manager.go
- utils/bash/bash_commands.go
- utils/config/config.go
- utils/dependencies/dependencies.go
- utils/dependencies/dymd.go
- utils/dependencies/eibc-client.go
- utils/dependencies/relayer.go
- utils/dependencies/rollapp.go
- utils/eibc/delegation.go
- utils/eibc/eibc.go
- utils/eibc/groups.go
- utils/eibc/keys.go
- utils/eibc/policies.go
- utils/keys/balances.go
- utils/relayer/relayer.go
- utils/sequencer/sequencer.go
- utils/templates/templates.go
- utils/tx/tx.go
---
For Author:
---
For Reviewer:
---
> feat: new eibc client integration

- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> feat: add support for whitelisted relayers

- cmd/eibc/init/init.go
fix: prompts user continuously for to fund the wallet fix:
---
For Author:
---
For Reviewer:
---
> fix: eibc client config settings

- cmd/relayer/setup/setup.go
- cmd/rollapp/setup/setup.go
- cmd/rollapp/start/start.go
- cmd/services/restart/restart.go
- cmd/services/start/start.go
- relayer/create_ibc_channel.go
- utils/genesis/genesis.go
- utils/keys/keyring_backend.go
- utils/keys/relayer.go
- utils/relayer/config.go
- utils/relayer/newibc.go
- utils/relayer/relayer.go
- utils/roller/roller.go
- utils/sequencer/sequencer.go
- utils/sequencer/types.go
---
For Author:
---
For Reviewer:
---
> feat: refactor relayer whitelist, move to ibc setup flow

- cmd/eibc/init/init.go
- cmd/eibc/start/start.go
- utils/eibc/types.go
---
For Author:
---
For Reviewer:
---
> fix(eibc): eibc existing roller config 

- cmd/rollapp/init/utils.go
- utils/keys/sequencer.go
---
For Author:
---
For Reviewer:
---
> fix: rollapp's mock backend initialization

- cmd/da-light-client/update/update.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/drs/drs.go
- cmd/rollapp/drs/update/update.go
- cmd/rollapp/rollapp.go
- utils/archives/archives.go
- utils/dependencies/dependencies.go
- utils/firebase/firebase.go
- utils/rollapp/bechprefix.go
- utils/sequencer/sequencer.go
- utils/service_manager/service.go
---
For Author:
---
For Reviewer:
---
> feat: add command that will update `rollappd` to latest drs commit

- cmd/eibc/init/init.go
---
For Author:
---
For Reviewer:
---
> fix: remove example rollapp record during init

- cmd/relayer/start/start.go
- utils/archives/archives.go
---
For Author:
---
For Reviewer:
---
> fix: dependency installation

- cmd/rollapp/setup/setup.go
---
For Author:
---
For Reviewer:
---
> fix: excessive settlement gas price

- utils/dependencies/eibc-client.go
---
For Author:
---
For Reviewer:
---
> chore(eibc): update eibc client version to latest rc

- cmd/relayer/setup/setup.go
- utils/dependencies/celestia.go
---
For Author:
---
For Reviewer:
---
> fix: install relayer binary as part of relayer setup

- cmd/relayer/setup/setup.go
- cmd/rollapp/sequencer/bond/decrease/decrease.go
- utils/filesystem/filesystem.go
- utils/keys/relayer.go
- utils/relayer/relayer.go
- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> fix: support os keyring for relayer whitelisting

- cmd/rollapp/setup/setup.go
- utils/config/config.go
---
For Author:
---
For Reviewer:
---
> fix: handle custom env manual input gas price

- cmd/eibc/init/init.go
- utils/dymint/dymint.go
---
For Author:
---
For Reviewer:
---
> chore: add quality of life improvements

- cmd/consts/consts.go
- cmd/consts/dymension.go
- cmd/rollapp/setup/setup.go
---
For Author:
---
For Reviewer:
---
> fix: increase necessary balance

- utils/sequencer/sequencer.go
- utils/sequencer/types.go
fixes #1140 
---
For Author:
---
For Reviewer:
---
> fix(fullnode): fix when retrieving  list p2p addresses + filter by bonded + opted in

- utils/dependencies/relayer.go
---
For Author:
---
For Reviewer:
---
> fix(deps): bump relayer binary version

- relayer/create_ibc_channel.go
- utils/eibc/eibc.go
fix some function names in comment
> chore: fix some function names in comment

- utils/sequencer/sequencer.go
---
For Author:
---
For Reviewer:
---
> fix: min sequencer bond from ra

- cmd/rollapp/drs/update/update.go
- cmd/rollapp/migrate/migrate.go
- cmd/rollapp/setup/setup.go
- utils/config/tomlconfig/toml.go
- utils/upgrades/evm-upgrades.go
---
For Author:
---
For Reviewer:
---
> fix: upgrade handler flow

- cmd/rollapp/start/start.go
- cmd/rollapp/status/status.go
- utils/eibc/operatormetadata.go
---
For Author:
---
For Reviewer:
---
> fix: move non base64 metadata into moniker of the new metadata

- utils/rollapp/bechprefix.go
---
For Author:
---
For Reviewer:
---
> fix: drs flag parsing

- cmd/consts/consts.go
- cmd/rollapp/setup/setup.go
- cmd/rollapp/start/start.go
- cmd/services/restart/restart.go
- cmd/services/start/start.go
- utils/sequencer/balance.go
feat: prompt for funding upon interacting with rollapp process
close #1171
---
For Author:
---
For Reviewer:
---
> feat: require only the bond amount during bond

- cmd/relayer/setup/setup.go
- utils/genesis/genesis.go
---
For Author:
---
For Reviewer:
---
> fix: optimize drs retrieval from genesis

- .gitignore
---
For Author:
---
For Reviewer:
---
> feat: ignore ds store

- cmd/config/init/rollapp.go
- cmd/consts/consts.go
- cmd/relayer/setup/setup.go
- cmd/rollapp/init/utils.go
- sequencer/config.go
- utils/genesis/genesis.go
---
For Author:
---
For Reviewer:
---
> feat: fetch min gas price from params

- cmd/config/config.go
- cmd/config/set/config.go
- cmd/config/set/hub_rpc.go
- cmd/config/set/set.go
- cmd/root.go
- cmd/services/restart/restart.go
- sequencer/config.go
- utils/healthagent/healthagent.go
- utils/sequencer/sequencer.go
- utils/service_manager/service.go
---
For Author:
---
For Reviewer:
---
> feat: add config setters

- cmd/config/init/rollapp.go
- cmd/relayer/setup/setup.go
- utils/rollapp/rollapp.go
---
For Author:
---
For Reviewer:
---
> fix:update rel and eibc flows for token less

- cmd/config/init/flags.go
- cmd/consts/dymension.go
- cmd/eibc/init/init.go
- cmd/rollapp/init/init.go
- data_layer/da_layer.go
- utils/config/propmts.go
- utils/keys/keyring_backend.go
- utils/relayer/relayer.go
---
For Author:
---
For Reviewer:
---
> feat: add blumbus testnet to roller

- cmd/config/set/config.go
- cmd/rollapp/sequencer/metadata/update/update.go
---
For Author:
---
For Reviewer:
---
> fix: minimum gas price setting in app.toml

- cmd/observability/export/templates/grafana/dashboard.json
---
For Author:
---
For Reviewer:
---
> chore: update grafana dasboard with new metrics

- cmd/rollapp/setup/setup.go
- cmd/rollapp/start/start.go
- utils/genesis/genesis.go
---
For Author:
---
For Reviewer:
---
> fix: validate checksum upon setup and start

- data_layer/celestia/celestia.go
---
For Author:
---
For Reviewer:
---
> fix: mainnet gas prices for dym and tia

- cmd/rollapp/sequencer/metadata/update/update.go
- utils/sequencer/types.go
---
For Author:
---
For Reviewer:
---
> fix: sequencer metadata update when snapshot is added

- cmd/relayer/setup/setup.go
- cmd/rollapp/drs/update/update.go
- cmd/rollapp/init/init.go
- utils/dependencies/dependencies.go
- utils/firebase/drs.go
---
For Author:
---
For Reviewer:
---
> feat: add drs version split between testnets and mainnet

- cmd/rollapp/init/utils.go
---
For Author:
---
For Reviewer:
---
> feat: add an easy way to back up the sequencer validator key

- cmd/services/restart/restart.go
- cmd/services/start/start.go
- utils/service_manager/service.go
Close #1255 
---
For Author:
---
For Reviewer:
---
> fix: roller rollapp services restart

- utils/config/jsonconfig/json.go
Corrected "upating" to "updating" in json.go.
> fix typo json.go

- cmd/config/init/keys.go
- cmd/consts/da.go
- cmd/eibc/init/init.go
- cmd/rollapp/init/init.go
- data_layer/celestia/celestia.go
- data_layer/celestia/lightclient/lightclient.go
- utils/tx/tx.go
Close: #1250 #1251 #1252 
---
For Author:
---
For Reviewer:
---
> feat: save user from stuck when RPC Endpoint not working and improve UI

- cmd/eibc/init/init.go
> fix(eibc): `max_orders_per_tx` should be 1 by default

- cmd/rollapp/setup/setup.go
- utils/config/prompts.go
- utils/relayer/relayer.go
---
For Author:
---
For Reviewer:
---
> feat(init): require custom hub endpoint for mainnet

- cmd/relayer/setup/setup.go
- cmd/rollapp/setup/setup.go
- data_layer/da_layer.go
- utils/genesis/genesis.go
---
For Author:
---
For Reviewer:
---
> feat(da): dymint da config depending of DRS

- cmd/relayer/status/status.go
- cmd/rollapp/keys/list/list.go
- cmd/root.go
- cmd/services/start/alert_agent.go
- utils/keys/key_config.go
- utils/keys/key_info.go
- utils/keys/relayer.go
---
For Author:
---
For Reviewer:
---
> feat: list all dymension keys using `roller keys list` command

- cmd/alert-agent/alert-agent.go
- cmd/alert-agent/init/init.go
- cmd/alert-agent/start/start.go
- cmd/consts/consts.go
- cmd/root.go
- cmd/services/load/load.go
- cmd/services/start/alert_agent.go
- cmd/services/start/start.go
- utils/dependencies/alert-manager.go
- utils/dependencies/dependencies.go
---
For Author:
---
For Reviewer:
---
> feat: add alert-agent integration

- cmd/rollapp/setup/setup.go
---
For Author:
---
For Reviewer:
---
> fix(da): da config fix

- cmd/services/load/load.go
- utils/config/scripts/scripts.go
- utils/config/scripts/types.go
---
For Author:
---
For Reviewer:
---
> fix: add support for custom home directory when loading systemd services

- utils/dymint/dymint.go
---
For Author:
---
For Reviewer:
---
> fix(relayer): fix update dymint config for new drs relayer setup

- cmd/da-light-client/update/update.go
- data_layer/celestia/celestia.go
- utils/dependencies/celestia.go
- utils/firebase/binaries.go
---
For Author:
---
For Reviewer:
---
> feat(celestia): support `v0.21.5` of celestia node

- cmd/rollapp/init/init.go
- utils/dependencies/dependencies.go
- utils/dependencies/solidity.go
- utils/rollapp/rollapp.go
…aries
---
For Author:
---
For Reviewer:
---
> fix(config): set the right version information for roller and rollapp binaries

- .github/workflows/lint.yml
- .golangci.yml
---
For Author:
---
For Reviewer:
---
> fix: linter workflow

- cmd/relayer/start/start.go
- cmd/relayer/status/status.go
Close #1254 #1249 
---
For Author:
---
For Reviewer:
---
> Retry when GetMetadataFromChain fails

- .github/workflows/test.yml
- .pre-commit-config.yaml
- cmd/relayer/setup/setup.go
- cmd/relayer/start/start.go
- relayer/channels.go
- relayer/keys.go
- utils/relayer/newibc.go
---
For Author:
---
For Reviewer:
---
> fix(relayer): support custom home dir

- cmd/oracle/utils/evm_deployer.go
- cmd/rollapp/drs/upgrade.go
---
For Author:
---
For Reviewer:
---
> fix: price oracle usdt feed

- utils/config/config.go
---
For Author:
---
For Reviewer:
---
> fix: url validation should support long TLDs

- cmd/oracle/priceoracle/configs/evm-config.yaml
- cmd/oracle/utils/evm_deployer.go
---
For Author:
---
For Reviewer:
---
> fix: price oracle feed for usd

- cmd/rollapp/setup/setup.go
---
For Author:
---
For Reviewer:
---
> fix: use snapshot only when they're present

- utils/config/prompts.go
Close #1308 
---
For Author:
---
For Reviewer:
---
> feat: prompt only if the config contains the default endpoint

- cmd/services/load/load.go
Close: #1306 
---
For Author:
---
For Reviewer:
---
> fix: set services before load them

- data_layer/weavevm/weavevm.go
---
For Author:
---
For Reviewer:
---
> fix: unmarshal da config

- data_layer/weavevm/weavevm.go
---
For Author:
---
For Reviewer:
---
> fix: logic check WeaveVM's balance

- cmd/consts/consts.go
- data_layer/weavevm/weavevm.go
---
For Author:
---
For Reviewer:
---
> feat: add logic GetDAAccData for WeaveVM

- data_layer/avail/avail.go
Close: #1291 
---
For Author:
---
For Reviewer:
---
> feat:  fetch the balance of the wallet before trying to continue

- cmd/rollapp/drs/upgrade.go
- data_layer/avail/appid.go
- utils/rollapp/rollapp.go
---
For Author:
---
For Reviewer:
---
> fix(drs_ugprade): fix da_config reinitialization for drs upgrade (namespace)

- utils/keys/relayer.go
Close #1104 
---
For Author:
---
For Reviewer:
---
> feat: import existing relayer keys

- cmd/oracle/priceoracle/configs/evm-config.yaml
- cmd/oracle/utils/evm_deployer.go
- cmd/services/load/load.go
- relayer/whitelisting.go
---
For Author:
---
For Reviewer:
---
> fix(proce-oracle): network names should be valid eth addresses

- cmd/alert-agent/config/config.go
- cmd/alert-agent/config/eibc.go
- cmd/alert-agent/init/init.go
- utils/eibc/authz.go
Close #1301 
---
For Author:
---
For Reviewer:
---
> feat: add alert when there is no LP for DYM or Native token

- cmd/consts/consts.go
- cmd/consts/da.go
- cmd/rollapp/init/utils.go
- data_layer/da_layer.go
- data_layer/loadnetwork/loadnetwork.go
- data_layer/loadnetwork/utils.go
- utils/roller/types.go
- utils/roller/validation.go
Close #1330 
---
For Author:
---
For Reviewer:
---
> chore: rename weavevm to loadnetwork 

- cmd/consts/dymension.go
- cmd/consts/types.go
- cmd/eibc/fulfill/order/order.go
- cmd/eibc/init/init.go
- cmd/rollapp/init/init.go
- cmd/rollapp/init/utils.go
- cmd/rollapp/sequencer/bond/decrease/decrease.go
- cmd/rollapp/sequencer/bond/increase/increase.go
- cmd/rollapp/sequencer/bond/unbond/unbond.go
- cmd/rollapp/sequencer/metadata/update/update.go
- utils/config/config.go
- utils/eibc/operatormetadata.go
- utils/sequencer/sequencer.go
- utils/tx/tx.go
Close #1313 
---
For Author:
---
For Reviewer:
---
> feat: add wsUrl optional field and modify MonitorTransaction function

- cmd/oracle/priceoracle/configs/evm-config.yaml
- cmd/oracle/utils/evm_deployer.go
---
For Author:
---
For Reviewer:
---
> fix: update price oracle deployment

- cmd/oracle/priceoracle/deploy.go
- cmd/oracle/utils/evm_deployer.go
- cmd/relayer/setup/setup.go
- utils/keys/relayer.go
---
For Author:
---
For Reviewer:
---
> fix(price-oracle): dependencies, property rename

- data_layer/bnb/bnb.go
---
For Author:
---
For Reviewer:
---
> fix: update dymint config for BNB

- cmd/services/start/start.go
- data_layer/aptos/aptos.go
- data_layer/aptos/utils.go
---
For Author:
---
For Reviewer:
---
> fix: update dymint config for APT

- cmd/services/start/start.go
- data_layer/sui/sui.go
- data_layer/sui/utils.go
---
For Author:
---
For Reviewer:
---
> fix: update dymint config for Sui

- utils/eibc/operatormetadata.go
fix comment
---
For Author:
---
For Reviewer:
---
> chore: fix comment

- cmd/config/set/config.go
- cmd/config/set/da.go
- cmd/config/set/set.go
- sequencer/config.go
Close: #1229 
---
For Author:
---
For Reviewer:
---
> feat: config set da node

- cmd/config/set/da.go
---
For Author:
---
For Reviewer:
---
> feat: handle config set da for other DAs

- cmd/consts/consts.go
- cmd/consts/da.go
- cmd/rollapp/init/utils.go
- data_layer/aptos/aptos.go
- data_layer/avail/avail.go
- data_layer/bnb/bnb.go
- data_layer/da_layer.go
- data_layer/sui/sui.go
- data_layer/walrus/utils.go
- data_layer/walrus/walrus.go
- utils/roller/types.go
- utils/roller/validation.go
Close #1346 
---
For Author:
---
For Reviewer:
---
> feat: add Walrus DA support

- utils/genesis/genesis.go
---
For Author:
---
For Reviewer:
---
> fix: mint_denom has moved to minter

- relayer/create_ibc_channel.go
Close #1354 
---
For Author:
---
For Reviewer:
---
> feat: new genesis bridge flow

- data_layer/aptos/aptos.go
- data_layer/avail/avail.go
- data_layer/bnb/bnb.go
- data_layer/celestia/celestia.go
- data_layer/loadnetwork/loadnetwork.go
- data_layer/sui/sui.go
Close #1344 
---
For Author:
---
For Reviewer:
---
> feat: improve DAs UX

- cmd/rollapp/setup/setup.go
- data_layer/celestia/blockinfo.go
- data_layer/celestia/celestia.go
- data_layer/celestia/lightclient/lightclient.go
- data_layer/celestia/types.go
- go.mod
Close #1351 
---
For Author:
---
For Reviewer:
---
> fix: refactor GetSequencerDAConfig for Celestia

- cmd/consts/consts.go
- cmd/consts/da.go
- cmd/rollapp/setup/setup.go
- data_layer/da_layer.go
- data_layer/kaspa/kaspa.go
- data_layer/kaspa/utils.go
- utils/roller/types.go
- utils/roller/validation.go
Close #1358 
---
For Author:
---
For Reviewer:
---
> feat: add Kaspa DA support

- cmd/rollapp/init/init.go
---
For Author:
---
For Reviewer:
---
> fix: correctly report errors from IsRegistered to avoid <nil>

- cmd/rollapp/keys/list/list.go
- utils/keys/key_info.go
---
For Author:
---
For Reviewer:
---
> feat: show da wallet address in `keys list`

- cmd/rollapp/setup/setup.go
- data_layer/celestia/lightclient/lightclient.go
- utils/genesis/genesis.go
- utils/rollapp/iro/iro.go
- utils/rollapp/rollapp.go
---
For Author:
---
For Reviewer:
---
> fix: genesis checksum check, da-light-client
