dymensionxyz/roller

cmd/config/init/prompt_existing_root.go
test/config/init/init_test.go

---
For Author:
---
For Reviewer:
---

fix: Fixed running `roller config init` when root dir does not exist

---

cmd/config/init/flags.go
cmd/config/init/init.go
test/config/init/goldens/init_with_flags/relayer/config/config.yaml
test/config/init/goldens/init_with_flags/rollapp/config/client.toml
test/config/init/goldens/init_with_flags/rollapp/config/genesis.json
test/config/init/goldens/init_without_flags/relayer/config/config.yaml
test/config/init/goldens/init_without_flags/rollapp/config/client.toml
test/config/init/goldens/init_without_flags/rollapp/config/genesis.json
test/config/init/init_test.go

---
For Author:
---
For Reviewer:
---

fix: Add rollapp ID `xxxx_num_num` enforcement on `roller config init`

---

cmd/config/init/DALightClient.go
cmd/config/init/consts.go
cmd/config/init/flags.go
cmd/config/init/genesis.go
cmd/config/init/init.go
cmd/config/init/keys.go
cmd/config/init/output.go
cmd/config/init/relayer.go
cmd/config/init/rollapp.go
cmd/config/init/unique_rollapp_id.go
cmd/consts/consts.go
cmd/da-light-client/start/start.go
cmd/register/bash_commands.go
cmd/register/register.go
cmd/relayer/relayer.go
cmd/relayer/start/start.go
cmd/root.go
cmd/run/run.go
cmd/sequencer/start/start.go
cmd/utils/bash_commands.go
cmd/utils/config.go
cmd/utils/error_handling.go
cmd/utils/keys.go
test/config/init/goldens/init_with_flags/relayer/config/config.yaml
test/config/init/goldens/init_without_flags/relayer/config/config.yaml
test/config/init/init_test.go
test/config/init/testutils/keys.go
test/config/init/testutils/rollapp.go

---
For Author:
---
For Reviewer:
---

feat: Add IBC channel creation capability from `roller relayer start` command

---

cmd/config/init/genesis.go
cmd/config/init/init.go
cmd/config/init/keys.go
cmd/config/init/output.go
cmd/config/init/relayer.go
cmd/config/init/rollapp.go
cmd/consts/consts.go
cmd/da-light-client/start/start.go
cmd/keys/list/list.go
cmd/register/bash_commands.go
cmd/relayer/start/start.go
cmd/sequencer/start/start.go
cmd/utils/balance.go
cmd/utils/fetch_accounts_data.go
cmd/utils/keys.go
test/config/init/testutils/keys.go
test/config/init/testutils/rollapp.go

---
For Author:
---
For Reviewer:
---

fix: Removed addresses that doesn't require funding from roller config init output

---

cmd/config/init/consts.go
cmd/config/init/flags.go
cmd/config/init/genesis.go
cmd/config/init/init.go
cmd/config/init/keys.go
cmd/config/init/rollapp.go
cmd/consts/consts.go
cmd/relayer/start/create_ibc_channel.go
cmd/sequencer/start/start.go
cmd/utils/keys.go

---
For Author:
---
For Reviewer:
---

feat: support latest RDK on devnet

---

cmd/config/init/flags.go
cmd/config/init/init.go
cmd/config/init/interactive.go

---
For Author:
---
For Reviewer:
---

feat: accepts -i for interactive. arguments are mandatory

---

cmd/register/register.go

---
For Author:
---
For Reviewer:
---

feat: adding --force flag for sequencer registration

---

install.sh

---
For Author:
---
For Reviewer:
---

feat: install script compiles all dependencies locally

---

cmd/config/init/init.go
cmd/config/init/output.go
cmd/consts/consts.go
cmd/keys/export/export.go
cmd/keys/list/list.go
cmd/utils/bash_commands.go
cmd/utils/keys.go
data_layer/celestia/celestia.go
data_layer/da_layer.go
data_layer/damock/damock.go

---
For Author:
---
For Reviewer:
---

feat: Add option to export Celestia private key

---

cmd/config/init/genesis.go
cmd/config/init/rollapp.go

The rollapp genesis account is created in the `keyring-backend test`
But the default client setting is left intact (`os` by default)
It fixes the funds drainage possible through the RPC as discussed on #281 
---
For Author:
---
For Reviewer:
---

fix: setting keyring-backend os for the client

---

cmd/services/load/load.go

This PR removes the log file parameter from the roller services load command as it was causing conflicts with the internal service writing all logs to the same file, thereby breaking the application and being redundant
---
For Author:
---
For Reviewer:
---

chore: Remove log file parameter from roller services load command

---

cmd/relayer/channel/channel.go
cmd/relayer/channel/show/show.go
cmd/relayer/relayer.go

---
For Author:
---
For Reviewer:
---

feat: Add a `roller relayer channel show` command

---

cmd/config/init/genesis.go
cmd/config/init/rollapp.go
test/config/init/goldens/init_with_flags/rollapp/config/config.toml
test/config/init/goldens/init_with_flags/rollapp/config/genesis.json
test/config/init/goldens/init_without_flags/rollapp/config/config.toml
test/config/init/goldens/init_without_flags/rollapp/config/genesis.json
test/config/init/init_test.go
test/config/init/testutils/compare.go
test/config/init/testutils/rollapp.go

---
For Author:
---
For Reviewer:
---

feat: Add support for setting sequencer as sole governer by default

---

.github/workflows/build.yml

---
For Author:
---
For Reviewer:
---

fix: Switch from gvm to setup-go action in workflow

---

relayer/create_ibc_channel.go

---
For Author:
---
For Reviewer:
---

fix: adjusted timeouts. added retry loop over create channels

---

cmd/config/config.go
cmd/config/export/bech32.go
cmd/config/export/export.go
cmd/config/export/types.go
cmd/config/init/unique_rollapp_id.go
cmd/config/show/types.go
config/chainid.go

---
For Author:
---
For Reviewer:
---

feat: Add a `roller config export` command

---

.github/workflows/e2e.yml

---
For Author:
---
For Reviewer:
---

chore: Make e2e flow run only on a manual trigger

---

cmd/config/set/da.go
cmd/config/set/lc_rpc.go
cmd/config/set/rollapp_rpc.go
cmd/config/set/set.go

---
For Author:
---
For Reviewer:
---

feat: Add set functions to all rollapp ports

---

cmd/migrate/v_0_1_13.go
relayer/channels.go
relayer/config.go
relayer/connections.go

---
For Author:
---
For Reviewer:
---

fix: roller extarcts wrong active channel

---

cmd/migrate/v_0_1_12.go

When updating the DA config in the v0.1.12 migrate, we first created a newAvail and then moved the avail config file to the new location. This caused generating a new avail seed and saving it only in the dymint.toml config. 
---
For Author:
---
For Reviewer:
---

fix: Prevent generate new avail seed in `roller migrate`

---

.github/workflows/build.yml

---
For Author:
---
For Reviewer:
---

Chore: Ensure the Release Workflow Does Not Break the CI Workflow

---

cmd/config/init/consts.go
cmd/config/init/denom_metadata.go
cmd/config/init/genesis.go
cmd/config/init/relayer.go
cmd/consts/consts.go
cmd/da-light-client/start/start.go
cmd/migrate/migrate.go
cmd/migrate/v1_0_00.go
cmd/relayer/start/start.go
cmd/sequencer/start/start.go
cmd/tx/register/bash_commands.go
cmd/utils/bash_commands.go
compile_locally.sh
relayer/commands.go
relayer/config.go
relayer/create_ibc_channel.go
test/config/init/goldens/init_with_flags/relayer/config/config.yaml
test/config/init/goldens/init_without_flags/relayer/config/config.yaml
test/config/init/testutils/relayer.go

---
For Author:
---
For Reviewer:
---

feat!: Add support for standard ibc

---

cmd/config/init/consts.go
cmd/consts/consts.go
relayer/clients.go
relayer/create_ibc_channel.go
sequencer/commands.go

This PR improves substantially the channel creation.
Channel creation is now done < 3 mins. 
It removes unnecessary code which used the old assumption of the forked ibc and changed the chain block production to use send fund commands from sequencer to itself vs update-client which would introduce problems such as account sequence mismatch and header heights coordination between received ibc packet header and already existing ibc header sent using the update command. 
---
For Author:
---
For Reviewer:
---

fix: ibc clients creation stuck 

---

.github/workflows/build.yml
README.md
compile_locally.sh

Moved the compilation of the Celestia & Cosmos SDK binaries to the compile_locally script for it to create a working roller version upon completion, and added instruction in the README file to run it before running the tests. They was separated initially because dymint didn't compile with go1.20, but it has already been addressed in the used version.
---
For Author:
---
For Reviewer:
---

chore: Add install binaries instruction to Readme testing section

---

.github/workflows/build.yml

---
For Author:
---
For Reviewer:
---

fix: Fixed go version in build workflow

---

README.md

---
The link to the Roller CLI documentation in the readme was broken. This PR updates it to point to the correct documentation URL (https://docs.dymension.xyz/build/roller/overview). This ensures users have access to the relevant information.
For Author:
---
For Reviewer:
---

chore(readme):Fix broken/outdated Roller CLI documentation link

---

cmd/config/init/flags.go
cmd/config/init/format.go
cmd/config/init/genesis.go
cmd/config/init/local_hub.go
cmd/rollapp/init/main.go
config/config.go
go.mod
go.sum
test/config/init/testutils/keys.go
utils/archives/archives.go

---
For Author:
---
For Reviewer:
---

feat: add rollapp init

---

cmd/config/init/genesis.go
cmd/consts/consts.go
cmd/rollapp/init/main.go

close #805 
---
For Author:
---
For Reviewer:
---

fix: add sequencer addresses to the generated genesis file

---

cmd/config/export/bech32.go
cmd/config/init/flags.go
cmd/config/init/format.go
cmd/config/init/genesis.go
cmd/config/init/keys.go
cmd/config/init/output.go
cmd/config/set/da.go
cmd/consts/consts.go
cmd/eibc/utils.go
cmd/keys/list/list.go
cmd/migrate/v1_0_05.go
cmd/rollapp/init/main.go
cmd/rollapp/init/utils.go
cmd/tx/claim/claim.go
cmd/tx/fund_faucet/fund_faucet.go
cmd/utils/balance.go
cmd/utils/fetch_accounts_data.go
cmd/utils/keys.go
data_layer/celestia/celestia.go
data_layer/da_layer.go
data_layer/damock/damock.go
relayer/config.go
relayer/create_ibc_channel.go

---
For Author:
---
For Reviewer:
---

feat: improve rollapp initialization

---

utils/keys/relayer.go

---
For Author:
---
For Reviewer:
---

feat: prompt to fund the relayer key continuously

---

cmd/relayer/start/start.go
relayer/config.go

---
For Author:
---
For Reviewer:
---

fix: relayer start

---

cmd/relayer/setup/setup.go
cmd/rollapp/drs/update/update.go
utils/dependencies/dependencies.go
utils/dependencies/rollapp.go
utils/firebase/firebase.go

---
For Author:
---
For Reviewer:
---

fix: update dependency retrieval to support different ra types

---

cmd/consts/dymension.go
cmd/consts/eibc.go
cmd/eibc/fulfill/feeshare/feeshare.go
cmd/eibc/fulfill/fulfill.go
cmd/eibc/fulfill/rollapps/remove/remove.go
cmd/eibc/fulfill/rollapps/set/set.go
cmd/eibc/init/init.go
sequencer/status.go
utils/eibc/config.go
utils/eibc/eibc.go
utils/eibc/operatormetadata.go
utils/eibc/types.go

---
For Author:
---
For Reviewer:
---

feat(eibc): store json object as the group and policy metadata

---

cmd/consts/da.go
cmd/rollapp/init/utils.go
data_layer/da_layer.go
data_layer/weavevm/utils.go
data_layer/weavevm/weavevm.go

Close #1233 
---
For Author:
---
For Reviewer:
---

feat: support WeaveVM
